export const CUSTOM_REVIEW_THRESHOLD = 100000;
export const pricingConfig = {
  services: {
    "Graphic Menu Design": { base: 999, includedPages: 1 },
    "Digital Menu": { base: 1999, includedPages: 0 },
    "Business Website": { base: 12999, includedPages: 3 },
    "Website + Digital Menu": { base: 17999, includedPages: 3 },
    "Custom Digital Solution": { base: 35000, includedPages: 0 },
    "AI / Interactive Experience": { base: 35000, includedPages: 0 },
    Other: { base: null, includedPages: 0 },
  },
  graphicMenuPages: {
    1: 999,
    2: 2199,
    3: 2799,
    4: 3499,
    5: 4199,
    perPageFromSix: 750,
  },
  digitalMenuTiers: {
    basic: { label: "Basic Digital Menu", amount: 1999 },
    branded: { label: "Branded Digital Menu", amount: 2499 },
    multi_category: { label: "Multi-category Digital Menu", amount: 3499 },
    advanced: { label: "Advanced Digital Menu", amount: 4999 },
  },
  websiteTiers: {
    basic: { label: "3-page Basic Website", amount: 12999 },
    standard: { label: "Standard Business Website", amount: 17999 },
    professional: { label: "Professional Website", amount: 24999 },
    advanced: { label: "Advanced Website", amount: 34999 },
  },
  additionalWebsitePage: 2000,
  digitalMenuVolume: {
    tiers: [
      {
        id: "small",
        min: 1,
        max: 10,
        estimatedPages: 1,
        amount: 0,
        label: "1–10 menu items",
      },
      {
        id: "medium",
        min: 11,
        max: 25,
        estimatedPages: 2,
        amount: 500,
        label: "11–25 menu items",
      },
      {
        id: "large",
        min: 26,
        max: 50,
        estimatedPages: 3,
        amount: 1000,
        label: "26–50 menu items",
      },
    ],
    veryLarge: {
      min: 51,
      itemsPerPage: 20,
      minimumPages: 4,
      baseAmount: 1500,
      perAdditionalPage: 750,
      label: "51+ menu items",
    },
    includedCategories: 3,
    additionalCategory: 300,
  },
  digitalMenuDesignWeights: {
    "modern-cafe": 150,
    "premium-restaurant": 350,
    "minimal-contemporary": 100,
    "modern-indian-restaurant": 300,
    "laundry-dry-cleaning": 100,
    "salon-beauty": 200,
    "local-service-business": 100,
    "custom-menu-design": 500,
  },
  graphicMenuDesignWeights: {
    "minimal-menu": 0,
    "modern-restaurant": 150,
    "premium-restaurant": 300,
    "modern-indian": 200,
    "cafe-bistro": 100,
    "luxury-elegant": 350,
    "bold-colorful": 200,
    rustic: 150,
    "traditional-indian": 250,
    "street-food": 150,
    "bakery-dessert": 150,
    "salon-beauty": 150,
    "corporate-business": 100,
    "local-service": 0,
    "creative-artistic": 300,
    "custom-menu-design": 500,
  },
  complexity: {
    content: { low: 0, medium: 1000, high: 2500 },
    functional: { low: 0, medium: 2000, high: 5000 },
    interaction: { low: 0, medium: 1500, high: 4000 },
    design: { low: 0, medium: 1000, high: 3000 },
  },
  urgency: { 6: 0.1, 5: 0.15, 4: 0.2, 3: 0.3, 2: 0.4, 1: 0.5 },
  minimumPriorityFee: 500,
  planningAllowancePercent: 0.08,
  planningAllowanceMinimum: 500,
};
export const featureCatalog = {
  qr_access: ["QR Menu Access", 0],
  whatsapp: [
    "WhatsApp Integration",
    {
      "Digital Menu": 300,
      "Business Website": 500,
      "Website + Digital Menu": 500,
    },
  ],
  call_button: ["Call Button", 200],
  google_maps: [
    "Google Maps / Location",
    {
      "Digital Menu": 200,
      "Business Website": 300,
      "Website + Digital Menu": 300,
    },
  ],
  pdf_download: ["PDF Download", 200],
  additional_category: ["Additional Menu Category", 300],
  large_content: ["Large Menu / High Content Volume", [500, 1000], "content"],
  custom_icons: ["Custom Icons / Illustrations", 500],
  custom_graphics: [
    "Custom Graphics",
    { "Digital Menu": 700, "Website + Digital Menu": 700, default: 500 },
  ],
  multiple_languages: [
    "Additional Language",
    { "Graphic Menu Design": 300, default: 500 },
  ],
  advanced_interaction: ["Advanced Interaction", [3000, 7000], "interaction"],
  premium_visual: ["Premium / Custom Visual Treatment", 500],
  image_cleanup: ["Image Cleanup / Enhancement", 300],
  social_version: ["Mobile / Social Version", 400],
  extra_revision: ["Additional Revision Round", 300],
  additional_pages: ["Additional Pages", 0],
  contact_form: ["Contact / Enquiry Form", 750],
  gallery: ["Gallery", 1000],
  booking: ["Booking / Appointment", [4000, 7000], "functional"],
  payment: ["Payment Integration", [4000, 7000], "functional"],
  cms: ["CMS / Blog", 3000],
  analytics: ["Analytics Setup", 500],
  seo: ["SEO Setup", [2000, 4000], "content"],
  advanced_animation: ["Advanced Animation", [2000, 5000], "interaction"],
  api_integration: [
    "External / Custom API Integration",
    [3000, 10000],
    "functional",
  ],
  authentication: ["Authentication / Login", 5000],
  dashboard: ["Dashboard / Admin", 7500],
  database: ["Database-backed Functionality", 6000],
  automation: ["Automation", 5000],
  custom_workflows: ["Custom Workflows", [5000, 10000], "functional"],
  admin_panel: ["Custom Admin Panel", 7500],
  ai_api: ["Gemini / AI API Integration", 5000],
  ai_chatbot: ["AI Chatbot", 7500],
  ai_recommendation: ["AI Recommendation System", 10000],
  ai_content: ["AI Content Generation", [10000, 20000], "functional"],
  interactive_experience: ["Interactive Experience", 5000],
  webgl: ["WebGL / 3D Experience", [10000, 25000], "interaction"],
  advanced_3d: ["Advanced 3D", 20000],
  custom_interactions: [
    "Custom Interaction System",
    [10000, 20000],
    "interaction",
  ],
};
export const serviceFeatureIds = {
  "Graphic Menu Design": [
    "premium_visual",
    "custom_icons",
    "image_cleanup",
    "multiple_languages",
    "social_version",
    "extra_revision",
  ],
  "Digital Menu": [
    "qr_access",
    "whatsapp",
    "call_button",
    "google_maps",
    "pdf_download",
    "additional_category",
    "large_content",
    "custom_icons",
    "custom_graphics",
    "multiple_languages",
    "advanced_interaction",
  ],
  "Business Website": [
    "additional_pages",
    "contact_form",
    "whatsapp",
    "google_maps",
    "gallery",
    "booking",
    "payment",
    "cms",
    "analytics",
    "seo",
    "advanced_animation",
    "advanced_interaction",
    "api_integration",
    "authentication",
    "dashboard",
  ],
  "Website + Digital Menu": [
    "additional_pages",
    "contact_form",
    "whatsapp",
    "call_button",
    "google_maps",
    "pdf_download",
    "additional_category",
    "large_content",
    "custom_graphics",
    "multiple_languages",
    "gallery",
    "booking",
    "payment",
    "cms",
    "analytics",
    "seo",
    "advanced_animation",
    "advanced_interaction",
    "api_integration",
    "authentication",
    "dashboard",
  ],
  "Custom Digital Solution": [
    "authentication",
    "dashboard",
    "database",
    "api_integration",
    "automation",
    "custom_workflows",
    "admin_panel",
    "payment",
    "booking",
    "advanced_interaction",
  ],
  "AI / Interactive Experience": [
    "ai_api",
    "ai_chatbot",
    "ai_recommendation",
    "ai_content",
    "api_integration",
    "interactive_experience",
    "webgl",
    "advanced_animation",
    "advanced_3d",
    "custom_interactions",
  ],
  Other: [],
};
export const knownFeatureIds = Object.keys(featureCatalog);
export const basePrices = Object.fromEntries(
  Object.entries(pricingConfig.services).map(([k, v]) => [k, v.base]),
);
export const serviceRanges = {};
