import { budgetRanges } from './budgetRanges.js';
export const formatINR=n=>n==null?'Discuss requirements':'₹'+Number(n).toLocaleString('en-IN');
const RULES={
 'Digital Menu':{base:1999,maxBase:4999,addons:[['many categories',500,/many|multiple|10\+|large|extensive/i],['mobile-ready QR/contact flow',500,/qr|whatsapp|mobile|link/i],['custom graphics/icons',750,/custom graphic|icon|illustration|premium/i]]},
 'Business Website':{base:7999,maxBase:12999,addons:[['extra pages/features',2500,/5-page|five page|gallery|maps|form|pricing/i],['advanced functionality',6000,/booking|payment|login|dashboard|cms|admin|automation/i]]},
 'Website + Digital Menu':{base:12999,maxBase:19999,addons:[['website scope',3000,/5-page|gallery|maps|form|pricing/i],['menu complexity',1500,/menu|prices|categories|qr|whatsapp/i],['advanced functionality',6000,/booking|payment|login|dashboard|cms|admin|automation/i]]}
};
export function estimateProject(data={}){const service=String(data.service||'');const rule=RULES[service];if(!rule)return{service,min:null,max:null,currency:'INR',requiresCustomDiscussion:true,label:'Custom estimate required',confidence:'discussion-required',breakdown:[{label:'Custom scope review',amount:null}],estimateVersion:'jcc-2026-01'};const text=String(data.requirementsText||'');let add=0,breakdown=[{label:'Base service',amount:rule.base}];for(const [label,amount,re] of rule.addons){if(re.test(text)){add+=amount;breakdown.push({label,amount})}}const min=rule.base;const max=Math.max(Math.min(rule.maxBase+add,service==='Digital Menu'?5999:34999),rule.base+add);return{service,min,max,currency:'INR',requiresCustomDiscussion:false,label:`${formatINR(min)} – ${formatINR(max)}`,confidence:'rough-estimate',breakdown,estimateVersion:'jcc-2026-01'}}
export function compareBudget(data={},estimate){const b=budgetRanges.find(x=>x.id===data.clientBudgetRange);if(!b||!estimate||estimate.requiresCustomDiscussion)return 'Final estimate requires a requirements discussion.';if(b.max!==null&&b.max<estimate.min)return 'Your selected budget is below the current planning estimate. We can review the scope and see whether the project can be simplified to fit your budget.';if(b.min>estimate.max)return 'Your selected budget is above the current estimated range. We can use the additional budget for further features or refinement.';return 'Your selected budget overlaps with the estimated project range.'}
export function budgetLabel(id){return budgetRanges.find(x=>x.id===id)?.label||'—'}
