import { budgetRanges } from './budgetRanges.js';
export const formatINR = n => n == null ? 'Discuss requirements' : '₹' + Number(n).toLocaleString('en-IN');
const itemCount=t=>Number((String(t||'').match(/(\d+)\s*(item|items|menu)/i)||[])[1]||0);
const rules={
 'Digital Menu':{base:1999,buffer:700,cap:4999,addons:[{label:'QR / WhatsApp menu access',amount:500,test:/qr|whatsapp|link|online/i},{label:'Digital content volume',amount:700,test:t=>itemCount(t)>25||/many|multiple|large|categories|sections/i.test(t)},{label:'Mobile presentation refinement',amount:600,test:/mobile|responsive|interactive/i},{label:'Custom graphics / icon styling',amount:800,test:/custom graphic|icon|brand|photo/i}]},
 'Business Website':{base:7999,buffer:2500,cap:29999,addons:[{label:'Pages / section scope',amount:2500,test:/5-page|five page|gallery|pricing|services|about|maps|google maps/i},{label:'Enquiry / contact functionality',amount:1200,test:/form|enquiry|contact form|whatsapp/i},{label:'Advanced functionality',amount:6000,test:/booking|payment|login|dashboard|admin|cms|automation|api/i},{label:'Content/section complexity',amount:1500,test:/menu|items|catalog|products|portfolio/i}]},
 'Website + Digital Menu':{base:12999,buffer:3000,cap:39999,addons:[{label:'Website pages / sections',amount:2500,test:/5-page|five page|gallery|pricing|services|about|maps/i},{label:'Digital menu categories / QR flow',amount:1500,test:/menu|categories|prices|qr|whatsapp/i},{label:'Advanced functionality',amount:6000,test:/booking|payment|login|dashboard|admin|cms|automation|api/i}]}
};
function pass(test,text){return typeof test==='function'?test(text):test.test(text)}
export function estimateProject(data={}){const service=String(data.service||'');const rule=rules[service];if(!rule)return{min:null,max:null,label:'Custom estimate required',requiresCustomDiscussion:true,breakdown:[{label:'Custom requirement review',amount:null}],explanation:'This service needs a custom discussion before estimating.'};const text=String(data.requirementsText||'');let add=0;const breakdown=[{label:'Base service',amount:rule.base}];for(const a of rule.addons){if(pass(a.test,text)){add+=a.amount;breakdown.push({label:a.label,amount:a.amount})}}const min=rule.base+add;const max=Math.min(rule.cap,min+rule.buffer);breakdown.push({label:'Planning range allowance',amount:rule.buffer});return{min,max,label:`${formatINR(min)} – ${formatINR(max)}`,requiresCustomDiscussion:false,breakdown,explanation:`The lower end assumes the described scope with standard execution. The upper end allows reasonable extra content/layout complexity discovered during scope review. Visual direction alone does not increase pricing.`}}
export function budgetLabel(id){return budgetRanges.find(b=>b.id===id)?.label||'—'}
export function compareBudget(data={},estimate){const b=budgetRanges.find(x=>x.id===data.clientBudgetRange);if(!b||!estimate||estimate.requiresCustomDiscussion)return 'Final estimate requires a requirements discussion.';if(b.max!==null&&b.max<estimate.min)return 'Your selected budget is below the current planning estimate. The full feature list fits the estimated range; if the budget is reduced, some features/content/revisions may need to be simplified.';if(b.min>estimate.max)return 'Your selected budget is above the current estimated range. The extra budget can support more refinement or added features.';return 'Your selected budget overlaps with the estimated project range.'}
